name: Build EdgeLine Press Kit

on:
  workflow_dispatch: {}   # ← adds the "Run workflow" button

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pillow moviepy numpy

      - name: Generate brand kit
        run: |
          python tools/generate_brand_kit.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: EdgeLine_Press_Kit
          path: artifacts/
