[theme]
base="dark"
primaryColor="#D4AF37"
backgroundColor="#000000"
secondaryBackgroundColor="#111111"
textColor="#FFFFFF"

[browser]
gatherUsageStats=false
favicon="https://raw.githubusercontent.com/Dylanjackson75/edgeline-live/main/assets/favicon.png"
