[theme]
base = "dark"
primaryColor = "#D4AF37"
backgroundColor = "#000000"
secondaryBackgroundColor = "#111111"
textColor = "#FFFFFF"

[server]
headless = true

[ui]
favicon = "assets/edgeline_logo_dark.png"
