[theme]
base="dark"
primaryColor="#D4AF37"
backgroundColor="#000000"
secondaryBackgroundColor="#111111"
textColor="#FFFFFF"

[server]
headless=true
enableCORS=false

[browser]
gatherUsageStats=false
favicon="assets/favicon.png"
